### ISSUE TITLE
json: cannot unmarshal number 1479321693.0 into Go value of type uint32

### ISSUE THREAD

**Issue by vascocosta** [jzelinskie/geddit#26]
I'm getting this error when calling session.Frontpage since one of the last commits, where apparently float64 was replaced by uint32 in some structures.

**Comment by voigt** [comment]
Just wanted to file the same issue.
@jzelinskie did the change because of #25 - obviously I was wrong with saying reddit always sends an integer.

I'm very sorry. To be honest I still not got whats wrong here - according to their API they send a number of type "long" - which is an integer to me...

However, with Float64 both issues should be solved.

**Comment by jzelinskie** [comment]
Sounds like float64 it is.

Thanks for the report!
